theme: jekyll-theme-cayman
url: https://gaa101.github.io/
baseurl: /jk-assignment/
title: Test Jekyll site
description: This is my first Jekyll site
instagram: "http://instagram.com/username"
author: Gio Aprigliano
